### ISSUE TITLE
Último ajuste a revisar.

### ISSUE THREAD

**Issue by jpadilla90** [japsasir/iaw-practica-03#5]
El archivo "config.inc.php" en el front_end no está actualizando la variable $IP_PRIVADA_MYSQL al ejecutar el script, de ahí que tenga problemas para apuntar a "$mysqli" No obstante, si modificamos a mano esta línea en "/var/www/html/phpmyadmin/config.inc.php" e introducimos la IP correspondiente, podemos acceder sin problema a Php my admin.

**Comment by jpadilla90** [comment]
https://imgur.com/tLkaKIr

**Comment by josejuansanchez** [comment]
Compara el nombre de la variable que estás utilizando en la línea 10 y 92. ¿Ves alguna diferencia? :)

https://github.com/japsasir/iaw-practica-03/blob/567f65d61e899db7307021cf7265ee05e74688b0/front_end.sh#L10

https://github.com/japsasir/iaw-practica-03/blob/567f65d61e899db7307021cf7265ee05e74688b0/front_end.sh#L92

**Comment by jpadilla90** [comment]
Pues justo era eso, gracias por señalarme la línea. Ya realiza la conexión a phpmyadmin, entra con lamp_user y lamp_password sin problema. Aunque tengo muchas ganas de darle carpetazo a la práctica, tengo que mencionar que en phpmyadmin aparecen un par de errores.

![PHP](https://i.imgur.com/DLfIxDF.png "PHP")
Si esto entra dentro de la normalidad, empiezo a ponerme al día con las nuevas.

**Comment by josejuansanchez** [comment]
El primer warning te está diciendo que no encuentra la extensión PHP mbstring. Revisa tu script para ver si se te ha olvidado instalar esta extensión (php-mbstring).

El segundo warning te está diciendo que necesita una frase secreta (blowfish_secret). Esto ocurre porque phpMyAdmin utiliza una cookie en el cliente y el contenido de la cookie está encriptada con un algoritmo que necesita una cadena aleatoria de 32 caracteres. 

Para solucionarlo, tendrás que editar el archivo de configuración de phpMyAdmin y asignar un valor aleatorio de 32 caracteres a la variable `blowfish_secret`.

**Comment by jpadilla90** [comment]
> Para solucionarlo, tendrás que editar el archivo de configuración de phpMyAdmin y asignar un valor aleatorio de 32 caracteres a la variable `blowfish_secret`.

He seguido estos pasos

He estado probando de muchas maneras, pero no se como usar el comando 'sed' para insertar un valor en el campo vacío que hay tras la línea blowfish_secret.

- Crear variable: BLOWFISH=`tr -dc A-Za-z0-9 < /dev/urandom | head -c 64`

- Intentar sustituir el valor nulo, pero solo he conseguido sustituir la línea: sed -i "s/blowfish_secret/$BLOWFISH/" /var/www/html/phpmyadmin/config.inc.php

- Varias operaciones con sed que he encontrado en StackOverflow, pero no han tenido éxito.

- Algunos compañeros me han sugerido importar directamente el archivo de configuración y moverlo, pero en esos casos no ha cogido correctamente las variables declaradas al inicio del script. He rotado entre comillas normales, dobles y ausencia de las mismas sin éxito.

- Finalmente he revertido a la opción original.

Me haría falta una ayudita en este punto o la opción de pasar por alto ese error y seguir con el resto de prácticas.

**Comment by josejuansanchez** [comment]
Ya casi lo tienes. 

No tienes reemplazar la cadena `blowfish_secret`, sino que tienes que asignarle un valor a la variable `$cfg['blowfish_secret']`. Cuando descargas el código fuente de phpMyAdmin verás que en esa variable no hay ningún valor asignado, estará así:

```php
$cfg['blowfish_secret'] = ''; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */
```
Lo que tienes que hacer es asignar un valor aleatorio, por ejemplo:

```php
$cfg['blowfish_secret'] = 'Valor aleatorio'; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */
```

He visto que has creado la variable `BLOWFISH` y le has asignado un valor aleatorio de 64 símbolos. Una vez que tienes el valor aleatorio generado lo único que tienes que hacer es añadirlo al archivo de configuración. Prueba con esto:

```bash
sed -i "s/'blowfish_secret'] = '';/'blowfish_secret'] = '$BLOWFISH';/" config.inc.php
```
Aquí estamos buscando la cadena `'blowfish_secret'] = '';`y la reemplazamos por `'blowfish_secret'] = '$BLOWFISH';`. De modo que el valor de la variable `BLOWFISH` quedará entre las comillas simples de la asignación de la variable.

**Comment by jpadilla90** [comment]
Ahora funciona perfecto. Voy a documentarlo correctamente. ¡Muchas gracias!
